### ISSUE TITLE
sqlite.Statement

### ISSUE THREAD

**Issue by ghost** [cztomsik/fridge#4]
Could you add to main.zig

```
pub const Statement = @import("sqlite.zig").Statement;
```

Then I can convert a row to a record using a separate fn...

```
fn statementToRecord(statement: sqlite.Statement) !*const Record {
    ...
}

```

That would allow me to

```
        while (true) {
            switch (try statement.step()) {
                .row => {
                    const record: *const Record = try statementToRecord(statement);
                    ...
                },
                .done => {
                    ...
                    break;
                },
            }
        }

```

**Comment by ghost** [comment]
To follow up, I vendored fridge and added the import in main.zig and it's working well for me.

**Comment by cztomsik** [comment]
Done, but please note that statement is low-level, does not support json fields (because those need allocator), and it also does not copy any data out (bc. allocator), so the sqlite statement locks the row until you are done. This may or may not be what you want, of course :) But if you are getting busy errors, it's probably a sign that you should use `fr.Session` instead

**Comment by ghost** [comment]
Thanks, That's all good to know. I'll recheck my code and I'll begin learning about the session.
